import { migrate } from 'drizzle-orm/postgres-js/migrator';
import { db } from './index';
import { resolve } from 'path';

/**
 * Run database migrations from the `./drizzle` folder.
 *
 * Uses drizzle-orm's migrator which reads the SQL migration files
 * generated by `drizzle-kit generate` and applies them in order.
 *
 * This should only be called on the deployment with RUN_MIGRATIONS=true.
 * All other deployments skip this entire function.
 *
 * Logs detailed status for observability in production.
 */
export async function runMigrations(): Promise<void> {
	const migrationsFolder = resolve(process.cwd(), 'drizzle');

	console.log('🔄 Running database migrations…');
	console.log(`   Migrations folder: ${migrationsFolder}`);

	try {
		await migrate(db, { migrationsFolder });
		console.log('✅ Migrations complete.');
	} catch (err) {
		console.error('❌ Migration failed:', err);
		throw err;
	}
}
